<div class='span2 well'>
    <h1> User </h1>
    <ul>
    <li><a target="_blank" href="/user/search">Search users</a></li>
    <li><a target="_blank" href="/user/search-roles">Roles</a></li>
    </ul>
</div>

<div class='span2 well'>
    <h1> Samx</h1>
    <ul>
    <li><a target="_blank" href="/samx/search">Search samx</a></li>
    <li><a target="_blank" href="/samx/search-comment">Search samx comments</a></li>
    <li><a target="_blank" href="/samx/new">New samx</a></li>
    </ul>
</div>

<div class='span2 well'>
    <h1> Common stuff</h1>
    <ul>
    <li><a target="_blank" href="/sitex/create-module">Create module</a></li>
    <li><a target="_blank" href="/queue/overview">Queue</a></li>
    <li>	       <a href='/fwdoc/queue'>queue docs</a> </li>
    <li>	       <a href='/fwdoc/index'>all docs</a> </li>
    <li><a href='/fwdoc/todo'>todos</a></li>
     <li><a href='/site/admin'>Admin</a></li>    	   
     <li><a href='/sitex/'>Sitex</a></li>    
    </ul>
    
</div>
