<div class='row'>
	<div class='col-md-3'>
	   <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Khách hàng</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
    	    <li><a href="/user/search" target="_blank">Quản lý khách hàng</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Video</h3>
          </div>
          <div class="panel-body admin-panel-body">
          	<ul>
    	    	<li><a href="/video/search" target="_blank">Tìm kiếm video</a></li>
    	    	<li><a href="/video/new" target="_blank">Tạo video mới</a></li>
    	    	<li><a href="/video/update-view" class='label label-default' target="_blank">Update Views</a></li>
    	    	<li><a href="/video/update-duration" class='label label-default' target="_blank">Update duration</a></li>
    	    </ul>
          </div>
        </div>
	</div>

	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Conf</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/conf/search" target="_blank">Search Conf</a></li>
            	<li><a href="/conf/new" target="_blank">New Conf</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
</div>