<div class='row'>
	<div class='col-md-3'>
	   <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Khách hàng</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
    	    <li><a href="/user/search" target="_blank">Quản lý khách hàng</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Video</h3>
          </div>
          <div class="panel-body admin-panel-body">
          	<ul>
    	    	<li><a href="/video/search" target="_blank">Tìm kiếm video</a></li>
    	    	<li><a href="/video/new" target="_blank">Tạo video mới</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Sản phẩm</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/product/search" target="_blank">Tìm kiếm sản phẩm</a></li>
            	<li><a href="/product/new" target="_blank">Tạo sản phẩm mới</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Quảng cáo</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/ad/search" target="_blank">Tìm kiếm quảng cáo</a></li>
            	<li><a href="/ad/new" target="_blank">Tạo quảng cáo mới</a></li>
    	    </ul>
          </div>
        </div>
	</div>
</div>

<div class='row'>
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Conf</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/conf/search" target="_blank">Search Conf</a></li>
            	<li><a href="/conf/new" target="_blank">New Conf</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Hóa đơn</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/bill/search" target="_blank">Tìm kiếm hóa đơn</a></li>
            	<li><a href="/bill/new" target="_blank">Tạo hóa đơn mới</a></li>
            	<li><a href="/bill/search-carts" target="_blank">Quản lý giỏ hàng</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Liên hệ</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/contact/search" target="_blank">Tìm kiếm liên hệ</a></li>
            	<li><a href="/contact/new" target="_blank">Tạo liên hệ mới</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Phản hồi</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/feedback/search" target="_blank">Quản lý phản hồi</a></li>
            	<li><a href="/feedback/new" target="_blank">Tạo phản hồi mới mới</a></li>
    	    </ul>
          </div>
        </div>
	</div>
</div>

<div class='row'>
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">So sánh giá</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/related/search" target="_blank">Quản lý so sánh giá</a></li>
            	<li><a href="/related/new" target="_blank">Tạo phản so sánh giá</a></li>
    	    </ul>
          </div>
        </div>
	</div>
</div>