<?php 
	$lu = Zend_Registry::get('user');
	$newVideos = isset($this->newVideos) ? $this->newVideos : array();
	$isWidget = (isset($this->is_widget) && $this->is_widget == 'widget') ? true:false;
	
	$page = isset($this->page) ? $this->page : 1;
	$filter = isset($this->filter) ? $this->filter : 1;
?>

<?php if($isWidget == false):?>
<div class="left-content">
	<div class="searchbar">
		<div class="search-left">
			<p>Tổng hợp cover hay nhất, hài nhất</p>
		</div>
		<div class="search-right">
			<form action='<?php echo SITE_URL?>/video/search-videos'>
				<input id="name" placeholder='Nhập video bạn muốn tìm?'
					class="form-control" type="text" value="" name="ac_name">
				<input id="_cl_step" type="hidden" value="" name="_cl_step">
				<input id="items_per_page" type="hidden" value="-1" name="items_per_page">
				<input id="_cl_submit" class="btn btn-large btn-primary" type="hidden"
					 value="Submit" name="_cl_submit">
			</form>
		</div>
		<div class="clear"> </div>
	</div>
	<div class="box">
<?php endif;?>
		<?php echo $this->render('/widget/video-list.phtml');?>
<?php if($isWidget == false):?>
	<div class="clear"> </div>
	</div>
</div>
<div class="right-content">
	<?php echo $this->render('/video/hot-videos.phtml');?>
<div class="clear"> </div>
	<?php echo $this->render('/video/new-videos.phtml');?>
</div>
<?php endif;?>
<div class="clear"> </div>