<?php 
    $row = $this->row;
    $user = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
    $newVideos = isset($this->newVideos) ? $this->newVideos : array();
    $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();
    $this->url = '/video/manage-video'
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>
<div class='row'>
	<div class='col-md-2'>
		<?php echo $this->render('/widget/user_menu.phtml');?>
	</div>
	<div class='col-md-10'>
		<div class="searchbar">
			<div class="search-left">
				<?php echo $this->render('/widget/search-box.phtml');?>
			</div>
			<div class="search-right">
				<p>Quản lý video</p>
			</div>
			<div class="clear"> </div>
		</div>
		
		<?php echo $this->render('/widget/manage-video-list.phtml');?>
		
		<div class="separator"> </div>
		<?php if($this->total > 0) :?>
	        <?php echo $this->render("widget/vd-pagination.phtml");?>
	    <?php endif;?>
	</div>
</div>