<?php echo sand_dev_info_phtml(__FILE__);?>
<?php $page = Zend_Registry::get('page');?>
<ul class='nav nav-pills'>
	<li <?php if ($page == 'video/index/new') echo "class='active';"?>><a href="/video/new">New</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'video/index/update') echo "class='active';"?>><a href="/video/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>"">Update</a></li>
	<?php endif;?>    
	<li <?php if ($page == 'video/index/search') echo "class='active';"?>><a href="/video/search">Search</a></li>
    <li <?php if ($page == 'video/index/search-comment') echo "class='active';"?>><a href="/video/search-comment">Search Comment</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'video/index/view') echo "class='active';"?>><a href="/video/<?php if (isset($this->row['id'])) echo "" . $this->row['id'];?>">View</a></li>
	<?php endif;?>
</ul>
<div class='separator'></div>
