<?php echo sand_dev_info_phtml(__FILE__);?>
<?php if(has_perm('sudo', null, '', $u)):?>
	<div class='row'>
	<?php echo sand_dev_info_phtml(__FILE__);?>
	
	<?php $page = Zend_Registry::get('page');
	?>
	<div class='col-md-12'>
	<?php echo $this->render('index/navbar.phtml');?>
	</div>
	<div class='col-md-6'>
	<?php if ($page == 'video/index/new'):?>
	<h1> Thêm video mới</h1>
	<?php else:?>
	<h1> Cập nhật video</h1>
	<?php endif;?>
	<?php $this->form->setAttrib('class', 'cl_ajax');?>
	<?php $this->form->setAttrib('method', 'POST');?>
		<div id='vd_form'>
			<?php echo $this->form;?>
		</div>
	</div>
	<div class='col-md-6'>
	<a href="#" id="preview_post_btn" class='btn btn-primary'>Xem trước</a>
	    <hr/>
	    <div id='preview_area'>
	    </div>
	</div>
	</div>
<?php else:?>
	<?php 
	    $row = $this->row;
	    $user = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
	    $newVideos = isset($this->newVideos) ? $this->newVideos : array();
	    $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();
		$this->form->setAttrib('class', 'cl_ajax');
	    $lu = $this->row;
	    $step = get_value('_cl_step', '');
	?>
	<script type="text/javascript">
	CL.NID = "<?php echo $row['id']; ?>";
	</script>
	<div class='row'>
		<div class='col-md-2'>
			<?php echo $this->render('/widget/user_menu.phtml');?>
		</div>
		<div class='col-md-7'>
			<div class="searchbar">
				<div class="search-left">
					<?php echo $this->render('/widget/search-box.phtml');?>
				</div>
				<div class="search-right">
					<p>Thêm video mới</p>
				</div>
				<div class="clear"> </div>
			</div>
			<div id='vd_form'>
				<?php echo $this->form;?>
			</div>
		</div>
		<div class='col-md-3'>
			<?php echo $this->render('/video/hot-videos.phtml');?>
			<div class="separator"> </div>
			<?php echo $this->render('/video/new-videos.phtml');?>
		</div>
	</div>
<?php endif;?>