<?php 
	$lu = Zend_Registry::get('user');
	$newVideos = isset($this->newVideos) ? $this->newVideos : array();
	$isWidget = (isset($this->is_widget) && $this->is_widget == 'widget') ? true:false;
	
	$page = isset($this->page) ? $this->page : 1;
	$filter = isset($this->filter) ? $this->filter : 1;
	$ac_name = get_value('ac_name');
	$this->is_search = true; 
?>

<?php if($isWidget == false):?>
<div class="left-content">
	<div class="searchbar">
		<div class="search-left">
			<?php echo $this->render('/widget/search-box.phtml');?>
		</div>
		<div class="search-right">
			<p>Kết quả tìm kiếm - <?php echo $ac_name;?></p>
		</div>
		<div class="clear"> </div>
	</div>
	<div class="box">
<?php endif;?>
        <?php if(isset($this->list) && count($this->list) > 0):?>
			<?php echo $this->render('/widget/video-list.phtml');?>
		<?php else:?>
			<div style='min-height: 30px;'></div>
			<?php echo $this->render('/widget/video-not-found.phtml');?>	
				
		<?php endif;?>
<?php if($isWidget == false):?>
	<div class="clear"> </div>
	</div>
</div>
<div class="right-content">
	<?php echo $this->render('/video/hot-videos.phtml');?>
<div class="clear"> </div>
	<?php echo $this->render('/video/new-videos.phtml');?>
</div>
<?php endif;?>
<div class="clear"> </div>