<div class='row'>
<?php echo sand_dev_info_phtml(__FILE__);?>

<div class='col-md-12'>
<?php echo $this->render('index/navbar.phtml');?>
</div>
</div>

<div class='row'>
<div class='col-md-2'>
    <div class='search_form well well-shallow'>
    <?php $this->form->setDisplayInline();
        $this->form->setAttrib('id' , 'search_form');
    ?>
    <?php echo $this->form;?>
    </div>
</div>

<div class='col-md-10'>
    <?php if($this->total > 0) :?>
        <?php echo $this->render("widget/pagination.phtml");?>
    <?php endif;?>
    
    <?php if($this->count > 0) :?>
	
    	<h3>Kết quả tìm kiếm</h3>
    	<?php //echo $this->render('widget/table.phtml');?>
    	<a href="/video/bulk-delete" id='bulk-delete' class="cl_ajax btn btn-xs btn-danger">
    		Xóa các video đã chọn</a>
    	<div class="clear"></div>
    	<br/>
        <table class="table table-striped table-bordered table-condensed">
        	<thead>
        		<tr>
        			<th><input type="checkbox" class="checkall"/></th>
        			<th>Image</th>
        			<th>Name</th>
        			<th>Status</th>
        			<th>Action</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($this->list as $row) :?>
        		<tr id="<?php echo $row['id'];?>">
        			<td><input type="checkbox" value="<?php echo $row['id'];?>" class="check-item" /></td>
        			<?php $imgLink = "http://img.youtube.com/vi/{$row['ytid']}/1.jpg";?>
        			<td><a href="<?php echo node_link('video',$row);?>">
        				<img src="<?php echo $imgLink;?>" title="video-name"
							style='width: 143px;height: 92px;'>
					</a></td>
        			<td><a href="<?php echo node_link('video',$row);?>"><?php echo $row['name'];?></a></td>
        			<td>
                        <div class="btn-group">
        			    	<a href="/video/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='queued') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group alert_success"> Queued </a>
        			    	<a href="/video/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='approved') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group alert_success"> Approved</a>
        			    </div> 
        			</td>
        			
        			<td>
        				<a href="/video/update?id=<?php echo $row['id']?>" class="btn btn-xs btn-default"><i class="icon-edit"></i> Edit</a>
        				<a href="/video/delete?id=<?php echo $row['id']?>" 
        					class="btn btn-xs btn-danger cl_ajax" _cl_get_metadata="remove_my_parent:2"
        					_cl_ajax_confirm='Are you sure you want to permanently delete this item?'
        					>
        					<i class="icon-remove"></i> Delete
        				</a>
        			</td>
        		</tr>
        		<?php endforeach;?>
        	</tbody>
        </table>
    <?php else:?>
    	<h3>No video found</h3>
    <?php endif;?>
</div>

</div>