<?php $lu = Zend_Registry::get('user');?>
<?php 
	$list = isset($this->list) ? $this->list : array();
 	$tag = isset($this->tag) ? $this->tag : array();
 	$newVideos = isset($this->newVideos) ? $this->newVideos : array();
 	$hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();
?>
<div class='row'>
	<div class="col-md-8">
		<div class="searchbar">
			<div class="search-left">
				<p><?php echo $tag['name'] ?> - Những bản cover hay nhất</p>
			</div>
			<div class="search-right">
				<form>
					<input type="text"><input type="submit" value="" />
				</form>
			</div>
			<div class="clear"> </div>
		</div>
		<div class="box">
		<?php if(count($list) > 0):?>
			<div class="grids">
			<?php $k = 0;?>
			<?php foreach ($list as $video):?>
				<?php if($k % 3 == 0 && $k > 0):?>
					</div>
					<div class="clear"> </div>
					<div class="grids">
				<?php endif;?>
					<?php $imgLink = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
					<div class="grid" style='margin-bottom: 4px;'>
						<a href="<?php echo node_link('video', $video);?>"><h3>
							<?php echo $video['name'];?></h3></a>
						<a href="<?php echo node_link('video', $video);?>">
							<img src="<?php echo $imgLink;?>" title="video-name"
							style='width: 243px;height: 152px;'>
							<img class="tidypics-photo-start" width="35px" height="25px" 
								src="<?php echo ASSETS_CDN?>/img/play_youtube.png" 
								style="left: 102px; position: absolute; top: 116px; width: 50px; 
								height: 40px; cursor: pointer;">
							</a>
						<div class="time">
							<?php $video['duration'] = isset($video['duration']) ? $video['duration'] : 0;?>
							<span><?php echo gmdate("H:i:s", (int)$video['duration']);?></span>
						</div>
						<div class="grid-info">
							<div class="video-share">
								<ul>
									<li><a href="#"><img src="<?php echo ASSETS_CDN?>/img/likes.png" title="links"></a></li>
									<li><a href="#"><img src="<?php echo ASSETS_CDN?>/img/link.png" title="Link"></a></li>
									<li><a href="#"><img src="<?php echo ASSETS_CDN?>/img/views.png" title="Views"></a></li>
								</ul>
							</div>
							<div class="video-watch">
								<a href="<?php echo node_link('video', $video);?>">Xem ngay</a>
							</div>
							<div class="clear"> </div>
							<div class="lables">
								<p>By:<a href="#"><?php echo $video['u']['name'];?></a></p>
							</div>
						</div>
					</div>
				<?php $k ++;?>
			<?php endforeach;?>
			</div>
		<?php endif;?>
		<div class="clear"> </div>
	</div>
		<div class="clear"> </div>
		<ul class="dc_pagination dc_paginationA dc_paginationA03">
		  <li><a href="#" class="first">First</a></li>
		  <li><a href="#" class="previous">Previous</a></li>
		  <li><a href="#">1</a></li>
		  <li><a href="#">2</a></li>
		  <li><a href="#" class="current">3</a></li>
		  <li><a href="#">4</a></li>
		  <li><a href="#">5</a></li>
		  <li><a href="#" class="next">Next</a></li>
		  <li><a href="#" class="last">Last</a></li>
		  
		</ul>
		<div class="clear"> </div>
	</div>
	<div class="col-md-4">
		<?php echo $this->render('/video/hot-videos.phtml');?>
	<div class="clear"> </div>
		<?php echo $this->render('/video/new-videos.phtml');?>
	</div>
</div>
<div class="clear"> </div>
