<?php 
    $row = $this->row;
    $lu = Zend_Registry::get('user');
    $related = isset($this->related) ? $this->related : array();
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>

<div class="inner-page">
	<div class="searchbar">
		<div class="search-left">
			<p>Chi tiết video</p>
		</div>
		<div class="search-right">
			<form>
				<input type="text"><input type="submit" value="" />
			</form>
		</div>
		<div class="clear"> </div>
	</div>
	<div class="title">
		<h3><?php echo $row['name'];?> </h3>
		<ul>
			<li><h4>Đăng bởi:</h4></li>
			<li><a href="#"><?php echo $row['u']['name'];?></a></li>
			<li><a href="#"><img src="http://test.local/videostube-pack/web/images/sub.png" title="subscribe" />subscribe</a></li>
		</ul>
	</div>
	<div class="video-inner videoview">
                <?php echo render_yt_embed_video($row['ytid'], 790, 450);?>
	</div>
	<div class="viwes">
		<div class="view-links">
			<ul>
				<li><h4>Chia sẻ:</h4></li>
				<li><a href="#"><img src="http://test.local/videostube-pack/web/images/f1.png" title="facebook" /></a></li>
				<li><a href="#"><img src="http://test.local/videostube-pack/web/images/t1.png" title="Twitter" /></a></li>
				<li><a href="#"><img src="http://test.local/videostube-pack/web/images/s1.png" title="Google+" /></a></li>
			</ul>
			<ul class="comment1">
				<li><a href="#">Bình luận(1)</a></li>
				<li><a href="#"><img src="http://test.local/videostube-pack/web/images/re.png" title="report" /><span>Báo cáo</span></a></li>
			</ul>
		</div>
		<div class="views-count">
			<?php $row['counter']['v'] = isset($row['counter']['v']) ? $row['counter']['v'] : 0;?>
			<p><span><?php echo number_format($row['counter']['v']);?></span> Lượt xem</p>
		</div>
		<div class="clear"> </div>
	</div>
	<div class="clear"> </div>
	<div class="video-details">
		<ul>
			<li><p>Được tải lên  <a href="#"><?php echo date('Y-m-d H:i:s', $row['ts']);?></a>
				 bỏi <a href="#"><?php echo $row['u']['name'];?></a></p></li>
			<li><span><?php echo $row['content'];?></span></li>
		</ul>
	</div>
	<div class="clear"> </div>
	<div class="tags">
		<ul>
			<li><h3>Tags:</h3></li>
			<?php if(isset($row['tags']) && count($row['tags']) > 0):?>
				<?php foreach ($row['tags'] as $tag):?><li>
					<li title='<?php echo $tag['name'];?>'><a href="#"><?php echo $tag['name'];?></a> </li>					
				<?php endforeach;?>
			<?php endif;?>
		</ul>
	</div>
	<div class="clear"> </div>
	<div class="related-videos">
		<h6>Video liên quan</h6>
	<div class="grids">
		<?php if(count($related) > 0):?>
			<?php foreach ($related as $video):?>
				<?php $imgLink = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
				<div class="grid" style='margin-bottom: 4px;'>
					<h3><?php echo $video['name'];?></h3>
					<a href="#"><img src="<?php echo $imgLink;?>" title="video-name"
						style='width: 243px;height: 152px;'></a>
					<div class="time">
						<?php $video['duration'] = isset($video['duration']) ? $video['duration'] : 0;?>
						<span><?php echo gmdate("H:i:s", (int)$video['duration']);?></span>
					</div>
					<div class="grid-info">
						<div class="video-share">
							<ul>
								<li><a href="#"><img src="http://test.local/videostube-pack/web/images/likes.png" title="links"></a></li>
								<li><a href="#"><img src="http://test.local/videostube-pack/web/images/link.png" title="Link"></a></li>
								<li><a href="#"><img src="http://test.local/videostube-pack/web/images/views.png" title="Views"></a></li>
							</ul>
						</div>
						<div class="video-watch">
							<a href="#">Xem ngay</a>
						</div>
						<div class="clear"> </div>
						<div class="lables">
							<p>By:<a href="#"><?php echo $video['u']['name'];?></a></p>
						</div>
					</div>
				</div>
			<?php endforeach;?>
		<?php endif;?>
		</div>
	</div>
	<div class="clear"> </div>
</div>
<div class="right-content">
	<div class="popular">
		<h3>Popular Videos</h3>
		<p><img src="http://test.local/videostube-pack/web/images/l1.png" title="likes" /> 10,000</p>
		<div class="clear"> </div>
	</div>
	<div class="grid1">
				<h3>Consectetur adipisicing elit</h3>
				<a href="#"><img src="http://test.local/videostube-pack/web/images/g7.jpg" title="video-name" /></a>
				<div class="time1">
					<span>2:50</span>
				</div>
				
				<div class="grid-info">
					<div class="video-share">
						<ul>
							<li><a href="#"><img src="http://test.local/videostube-pack/web/images/likes.png" title="links" /></a></li>
							<li><a href="#"><img src="http://test.local/videostube-pack/web/images/link.png" title="Link" /></a></li>
							<li><a href="#"><img src="http://test.local/videostube-pack/web/images/views.png" title="Views" /></a></li>
						</ul>
					</div>
					<div class="video-watch">
						<a href="#">Watch Now</a>
					</div>
					<div class="clear"> </div>
					<div class="lables">
						<p>Labels:<a href="#">Lorem</a></p>
					</div>
				</div>
			</div>
			<div class="clear"> </div>
</div>
<div class="clear"> </div>