<div class="popular">
	<h3>
		<a href="https://www.facebook.com/clipcoverhay" style='color: #FFF;'>
			Cover trên facebook</a></h3>
	<div class="clear"> </div>
</div>
<div class="fb-like-box" 
	data-href="https://www.facebook.com/clipcoverhay" 
	data-width="408" 
	data-height="200" 
	data-colorscheme="light" 
	data-show-faces="true" 
	data-header="false" 
	data-stream="false" 
	data-show-border="false">
</div>