    var CL = {};
    CL.metadata ={};
    CL.funcs = {};
    CL.GUEST_ID = <?php echo GUEST_ID;?>;
    CL.SAND_ASSETS_CDN = "<?php echo SAND_ASSETS_CDN;?>";
    CL.ASSETS_CDN = "<?php echo ASSETS_CDN;?>";
    CL.CODENAME = "<?php echo CODENAME;?>";
    CL.COOKIE_PREFIX = "<?php echo COOKIE_PREFIX;?>";
    CL.DOMAIN = "<?php echo DOMAIN;?>";
    CL.DEFAULT_AVATAR = "<?php echo DEFAULT_AVATAR_URL;?>";
	CL.page = "<?php echo Zend_Registry::get('page');?>"; 
	CL.APPLICATION_ENV = "<?php echo APPLICATION_ENV;?>";
	   