<form action='<?php echo SITE_URL?>/video/search-videos'>
	<input id="name" placeholder='Nhập video bạn muốn tìm?'
		class="form-control" type="text" value="" name="ac_name"
		style='width: 267px; height: 25px; float: left;'>
	<input id="_cl_step" type="hidden" value="" name="_cl_step">
	<input id="items_per_page" type="hidden" value="-1" name="items_per_page">
	<input id="_cl_submit" class="btn btn-large btn-primary" type="submit"
		 value="" name="_cl_submit">
</form>