<?php echo sand_dev_info_phtml(__FILE__);?>
<?php
	$lu = $this->row;
	$step = get_value('_cl_step', '');
?>
<?php 
	echo $this->form;
?>

<div id='preview' style='clear: both; width: 90px; min-width: inherit;'>
	Xem trước	
</div>
<div class='clear' style='min-height: 20px;'></div>
<div id="idcover" class="pfctncover">
<?php if($step == 'background'):?>
	<div class="filledImage border-img">
		<img class='avatar-preview' alt="" src="<?php echo $lu['background'];?>">
<?php elseif ($step == 'avatar'):?>
	<div class="pfavatar border-img" style='top: 0;'>
		<span class="avtholder" 
			style="background-image:url('<?php echo $lu['avatar'];?>');"> Hà Việt Đức</span>
<?php endif;?>
	</div>
</div>
<?php $this->inlineScript()->captureStart();?>
	//TODO: click preview change image in class avatar-preview
	
	//Show style background and 
	$("#preview").click(function(){
		var src = $(".display_avatar img").attr('src');
		<?php if($step == 'background'):?>
			$(".avatar-preview").attr('src', src);
		<?php else:?>
			$(".avtholder").css('background-image', "url('" + src + "')");
		<?php endif;?>
	});
	
<?php $this->inlineScript()->captureEnd();?>