<?php echo sand_dev_info_phtml(__FILE__);?>
<?php
	$lu = $this->row;
	$step = get_value('_cl_step', '');
?>
<?php 
/*
	if($step == 'background'){
		echo $this->form->background;
	}else if($step == 'avatar')
	{
		echo $this->form->avatar;
	}
	
	echo $this->form->_cl_submit;
 */
	echo $this->form;
?>

<div id='preview' style='clear: both; width: 90px; min-width: inherit;'>
	Xem trước	
</div>
<span id="output" onchange="changePositionTop()"></span>
<div class='separator-high'></div>
<div id="idcover" class="pfctncover">
	<?php if($step == 'background'):?>
		<div class="drag-cover">
	          <img src="<?php echo $lu['background'];?>"
	          		class='avatar-preview' 
	          		alt="<?php echo $lu['name'];?>" style="width:1024px; height:768px;"/>
	        </div>
		<?php /*
		<div class="filledImage border-img">
			<img class='avatar-preview' alt="" src="<?php echo $lu['background'];?>">
		*/?>
	<?php elseif ($step == 'avatar'):?>
		<div class="pfavatar border-img" style='top: 0;'>
			<span class="avtholder" 
				style="background-image:url('<?php echo $lu['avatar'];?>');"> Hà Việt Đức</span>
		</div>
	<?php endif;?>
</div>
<?php $this->inlineScript()->captureStart();?>
	//Show style background and 
	$("#preview").click(function(){
		var src = $(".display_avatar img").attr('src');
		<?php if($step == 'background'):?>
			$(".avatar-preview").attr('src', src);
		<?php else:?>
			$(".avtholder").css('background-image', "url('" + src + "')");
		<?php endif;?>
	});
	$(function(){
        $('.drag-cover').imagedrag({
          input: "#position_top",
          position: "middle",
          attribute: "html"
        });
    });
<?php $this->inlineScript()->captureEnd();?>
<?php $this->inlineScript()->appendFile(ASSETS_CDN . "js/jquery.imagedrag.js", 'text/javascript');?>
<style type="text/css">
	.drag-cover {
	    width: 938px;
	    height: 280px;
	    overflow: hidden;
	    margin: auto;
	    cursor: -webkit-grab;
}
</style>