<div style="" class="zml">
	<div class="zml_inner" style="">
		<div class="zml_toparea lmsection_heading">
			<div class="infouser">
				<a href="http://me.zing.vn/u/vietduc_angelboy" title="Hà Việt Đức" class="profileavt">
					<img src="http://d.1.s50.avatar.zdn.vn/avatar_files/d/5/7/d/vietduc_angelboy_50_14.jpg" alt="Hà Việt Đức">
				</a>
				<div class="profilename">
					<a data-username="vietduc_angelboy" data-uid="18099010" class="mevip" href="http://me.zing.vn/u/vietduc_angelboy">
						<span>
							<strong class="textname">Hà Việt Đức</strong>
							<!--<span class="levelicon"><strong class="levelsprt icolevel lv0"></strong></span>-->
						</span>
					</a>
				</div>
			</div>
		</div>
	
		<div class="zmmenu">
			<ul class="mhome">
				<li>
					<a href="/h/vietduc_angelboy" id="lm_news">
						<strong><span class="zmenuico_wrapper">
							<span class="mhome_icn zmenuico"></span></span>Clip của bạn</strong>
					</a>
				</li>
				
				<li>
					<a href="/jpt/?_src=m" id="lm_photo">
						<strong><span class="zmenuico_wrapper">
							<span class="mphoto_icn zmenuico"></span></span>Ảnh đại diện</strong>
					</a>
				</li>
				
				<li>
					<a href="/zbc?_src=m" id="lm_blog">
						<strong><span class="zmenuico_wrapper">
							<span class="mblog_icn zmenuico"></span></span>Cài đặt</strong>
					</a>
				</li>
				
				<li>
					<a href="http://appstore.zing.vn/?_src=m&amp;t=ls" id="lm_appstore">
						<strong><span class="zmenuico_wrapper">
							<span class="mappstore_icn zmenuico"></span></span>Ảnh bìa</strong>
					</a>
				</li>
				
				<li>
					<a href="http://me.zing.vn/u/lm?src=11" id="lm_mobile">
						<strong><span class="zmenuico_wrapper">
							<span class="mmobileapp_icn zmenuico"></span></span>Playist</strong>
					</a>
				</li>
		
			</ul>
		</div>
	</div>
</div>