<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
	$lu = Zend_Registry::get('user');
	$viewuser = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
?>
<?php 
	$avatar = (isset($viewuser['avatar']) && $viewuser['avatar'] !== '') ? $viewuser['avatar'] : default_avatar('user');
	$background = (isset($viewuser['background']) && $viewuser['background'] !== '') ? $viewuser['background'] : default_avatar('background');
	$subscribe = isset($lu['subscribe']) ? $lu['subscribe'] : array();
	$subscribed = false;
	if(count($subscribe) > 0){
		foreach ($subscribe as $u){
			if($u['id'] == $viewuser['id']){
				$subscribed = true;
				break;				
			}
		}
	}
	
	$subLink = "/user/subscribe?id={$viewuser['id']}";
	$unsubLink = "/user/unsubscribe?id={$viewuser['id']}";
?>
<div class="zm_pfcover">
	<div class="pfavatar">
		<a href="/u/vietduc_angelboy?f=1">
			<span class="avtholder" 
				style="background-image:url('<?php echo $avatar;?>');">
					<?php echo $viewuser['name'];?></span></a>
		
		    <?php if($lu['id'] == $viewuser['id']):?>
				<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=avatar" 
					class="bgeditavatar" title='Sửa avatar'>
					<p><em class="zmsprt zmico icoeditavatar"></em></p>
				</a>
			<?php endif;?>
		
	</div>
	
	<div id="idcover" class="pfctncover">
		<div class = "filledImage">
			<img src="<?php echo $background;?>" 
				style="-ms-interpolation-mode:bicubic;image-rendering:optimizeQuality;
				<?php 
					list($width, $height) = getimagesize($background);
					$heightFilledImage = 256;//height class filedImage img
					$widthFilledImage = 796;
					
					//Get height (chieu dai thuc cua anh ty le
					// voi chieu dai cua khung chua anh)
					$heightFilledImageNew = $widthFilledImage * $height/ $width;
					
					$gap = ($heightFilledImageNew - $heightFilledImage)/2;
					if($gap > 0){
						echo "margin-top: -{$gap}px;";
					}else{
						echo "margin-top: {$gap}px;";
					}
				?>" 
					id="idphotocover">
		   </div>
		   <?php if($lu['id'] == $viewuser['id']):?>
				<a class="ctneditcover" href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=background">
					<span class="zmsprt zmico icoeditcover"></span>Sửa ảnh bìa</a>
			<?php endif;?>
			<?php /*
				<div class='vd_ustatus'> 
					<div class='ustatus'>
						<?php if(isset($viewuser['ustatus'])) echo $viewuser['ustatus'];?>
					</div>
				</div>
			*/?>
				
			<div class="pfctnusername">
				<div class='ustatus'>
					<?php if(isset($viewuser['ustatus'])) echo $viewuser['ustatus'];?>
				</div>
				<a href="<?php echo user_link($viewuser);?>" 
					class="username">
					<?php echo $viewuser['name'];?></a>
			</div>
	</div>
	
	<div class="pfctnbtn">
		<div style='width: 100%;'>
			<span class="fl">
					Tham gia: <strong><?php echo date('m/d/Y', $viewuser['ts']);?></strong>
			</span>
			
			<span class="pull-right">
			<?php /*
				<a href='javascript:void(0);'>				
			*/?>
				<a href='<?php if($subscribed) 
							       echo $unsubLink; 
							   else 
							   	   echo $subLink;?>' 
			   	   class='cl_ajax sublink'>
					<button type="button" 
						class="btn btn-primary vd-is-buffered vd-button-branded sub-button
							<?php if($subscribed):?>vd-button-active<?php endif;?>">
						<span class="button-icon-wrapper">
							<img class="vd-button-icon" 
							src="<?php echo ASSETS_CDN;?>/img/youtube-icon-small.png">
						</span>
						
						<span class="vd-button-content">
							<span aria-label="
									<?php if($subscribed):?>Đã đăng ký<?php else:?>
										Chưa đăng ký<?php endif;?>" class="sub-label">
								<?php if($subscribed):?>Đã đăng ký<?php else:?>
									Chưa đăng ký<?php endif;?>
								</span>
						</span>
					</button>
				</a>
				<?php $subCount = isset($viewuser['counter']['s']) ? $viewuser['counter']['s'] : 0;?>
				<span class="subscribe-count" 
					data-count='<?php echo $subCount;?>'><?php echo $subCount;?></span>
			</span>
		</div>
	</div>
	
	<ul class="pfmenutab">
		<li id="playlist_video">
			<a href="javascript:void(0)" class="selected a_tab">
				Clip ưa thích</a></li>
		<li id="upload_video">
			<a href="javascript:void(0)" class='a_tab'>
				Clip bạn tải lên</a></li>
	   <?php /*
		<li id="subscribe_user">
			<a href="javascript:void(0)" class='a_tab'>
				Đã đăng ký</a></li>
	   */?>	
	</ul>
	<div class="clear"> </div>
</div>
<div class="clear"> </div>
<?php $this->inlineScript()->captureStart();?>
	$(".vd-button").mouseover(function(){
		var _this = $(this);
		if(_this.hasClass('vd-button-active')){
			if(_this.hasClass('sub-button')){
					_this.find(".sub-label").attr('aria-label', "Hủy đăng ký").html("Hủy đăng ký");
				}
		}else{
			if(_this.hasClass('sub-button')){
				_this.find(".sub-label").attr('aria-label', "Đăng ký").html("Đăng ký");
			}
		}
	});
	
	$(".vd-button").mouseout(function(){
		var _this = $(this);
		if(_this.hasClass('vd-button-active')){
			if(_this.hasClass('sub-button')){
					_this.find(".sub-label").attr('aria-label', "Đã đăng ký").html("Đã đăng ký");
				}
		}else{
			if(_this.hasClass('sub-button')){
				_this.find(".sub-label").attr('aria-label', "Chưa đăng ký").html("Chưa đăng ký");
			}
		}
	});
	
	$(".vd-button").on('click', function(){
		var _this = $(this);
		if(_this.hasClass('vd-button-active')){
			_this.removeClass('vd-button-active');

			var sub_count = $(".subscribe-count").attr('data-count');
			var new_count = parseInt(sub_count) - 1;
			$(".subscribe-count").attr('data-count', new_count);
			$(".subscribe-count").html(new_count);
			$(".sub-label").attr('aria-label', "Chưa đăng ký").html("Chưa đăng ký");
			//$(".sublink").attr('href', "<?php echo $subLink;?>");
		}else{
			_this.addClass('vd-button-active');
			
			var sub_count = $(".subscribe-count").attr('data-count');
			var new_count = parseInt(sub_count) + 1;
			$(".subscribe-count").attr('data-count', new_count);
			$(".subscribe-count").html(new_count);
			$(".sub-label").attr('aria-label', "Đã đăng ký").html("Đã đăng ký");
			//$(".sublink").attr('href', "<?php echo $unsubLink;?>");
		}
	});
<?php $this->inlineScript()->captureEnd();?>