<?php 
	$lu = Zend_Registry::get('user');
	$avatar = (isset($lu['avatar']) && $lu['avatar'] != '') ? $lu['avatar'] : default_avatar('user');
?>
<div style="" class="zml">
	<div class="zml_inner" style="">
		<div class="zml_toparea lmsection_heading">
			<div class="infouser">
				<a href="<?php echo user_link($lu);?>" title="<?php echo $lu['name'];?>" class="profileavt">
					<img src="<?php echo $avatar;?>" alt="<?php echo $lu['name'];?>">
				</a>
				<div class="profilename">
					<a class="mevip" href="<?php echo user_link($lu);?>">
						<span>
							<strong class="textname"><?php echo $lu['name'];?></strong>
						</span>
					</a>
				</div>
			</div>
		</div>
	
		<div class="zmmenu">
			<ul class="mhome">
				<li>
					<a href="/user/my-clip" id="lm_news"
						title='Clip của bạn'>
						<strong>
							<span class="zmenuico_wrapper">
								<span class="mhome_icn zmenuico"></span>
							</span>Clip của bạn</strong>
					</a>
				</li>
				
				<li>
					<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=avatar" id="lm_photo"
						title='Ảnh đại diện'>
						<strong>
							<span class="zmenuico_wrapper">
								<span class="mphoto_icn zmenuico"></span>
							</span>Ảnh đại diện</strong>
					</a>
				</li>
				
				<li>
					<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=account" id="lm_blog"
						title='Cập nhật tài khoản'>
						<strong>
							<span class="zmenuico_wrapper">
								<span class="mblog_icn zmenuico"></span>
							</span>Cập nhật tài khoản</strong>
					</a>
				</li>
				<li>
					<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=background" id="lm_appstore"
						title='Ảnh bìa'>
						<strong>
							<span class="zmenuico_wrapper">
								<span class="mappstore_icn zmenuico"></span>
							</span>Ảnh bìa</strong>
					</a>
				</li>
				
				<li>
					<a href="/user/favourite" id="lm_mobile"
						title='Clip ưa thích'>
						<strong>
							<span class="zmenuico_wrapper">
								<span class="mmobileapp_icn zmenuico"></span>
							</span>Clip ưa thích</strong>
					</a>
				</li>
		
			</ul>
		</div>
	</div>
</div>