<?php 
	$lu = Zend_Registry::get('user');
	$viewuser = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
?>
<?php 
	$avatar = (isset($viewuser['avatar']) && $viewuser['avatar'] !== '') ? $viewuser['avatar'] : default_avatar('user');
	$background = (isset($viewuser['background']) && $viewuser['background'] !== '') ? $viewuser['background'] : default_avatar('background');
?>
<div class="zm_pfcover">
	<div class="pfavatar">
		<a href="/u/vietduc_angelboy?f=1">
			<span class="avtholder" 
				style="background-image:url('<?php echo $avatar;?>');">
					<?php echo $viewuser['name'];?></span></a>
		
		    <?php if($lu['id'] == $viewuser['id']):?>
				<a href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=avatar" 
					class="bgeditavatar" title='Sửa avatar'>
					<p><em class="zmsprt zmico icoeditavatar"></em></p>
				</a>
			<?php endif;?>
		
	</div>
	
	<div id="idcover" class="pfctncover">
		<div class = "filledImage">
			<img src="<?php echo $background;?>" 
				style="-ms-interpolation-mode:bicubic;image-rendering:optimizeQuality;
				<?php 
					list($width, $height) = getimagesize($background);
					$heightFilledImage = 256;//height class filedImage img
					$widthFilledImage = 796;
					
					//Get height (chieu dai thuc cua anh ty le
					// voi chieu dai cua khung chua anh)
					$heightFilledImageNew = $widthFilledImage * $height/ $width;
					
					$gap = ($heightFilledImageNew - $heightFilledImage)/2;
					if($gap > 0){
						echo "margin-top: -{$gap}px;";
					}else{
						echo "margin-top: {$gap}px;";
					}
				?>" 
					id="idphotocover">
		   </div>
		   <?php if($lu['id'] == $viewuser['id']):?>
				<a class="ctneditcover" href="/user/update?id=<?php echo $lu['id'];?>&_cl_step=background">
					<span class="zmsprt zmico icoeditcover"></span>Sửa ảnh bìa</a>
			<?php endif;?>
			<?php /*
				<div class='vd_ustatus'> 
					<div class='ustatus'>
						<?php if(isset($viewuser['ustatus'])) echo $viewuser['ustatus'];?>
					</div>
				</div>
			*/?>
				
			<div class="pfctnusername">
				<div class='ustatus'>
					<?php if(isset($viewuser['ustatus'])) echo $viewuser['ustatus'];?>
				</div>
				<a href="<?php echo user_link($viewuser);?>" 
					class="username">
					<?php echo $viewuser['name'];?></a>
			</div>
	</div>
	
	<div class="pfctnbtn">
		<div style='width: 100%;'>
			<span class="fl">
					Tham gia: <strong><?php echo date('m/d/Y', $viewuser['ts']);?></strong>
			</span>
			
			<span class="pull-right">
			<?php /*
				<a href='/user/subscribe?id=<?php echo $viewuser['id'];?>' class='cl_ajax'>
			*/?>
				<a href='javascript:void(0);'>				
					<button type="button" 
						class="vd-button vd-is-buffered vd-button-branded">
						<span class="button-icon-wrapper">
							<img class="vd-button-icon" 
							src="<?php echo ASSETS_CDN;?>/img/youtube-icon-small.png">
						</span>
						
						<span class="vd-button-content">
							<span aria-label="Đăng ký" class="subscribe-label">
								Đăng ký
								</span>
						</span>
					</button>
				</a>
				<span class="subscribe-count" data-count='371'>371</span>
			</span>
		</div>
	</div>
	
	<ul class="pfmenutab">
		<li id="playlist_video">
			<a href="javascript:void(0)" class="selected a_tab">
				Clip ưa thích</a></li>
		<li id="upload_video">
			<a href="javascript:void(0)" class='a_tab'>
				Clip bạn tải lên</a></li>
				
		<li id="subscribe_user">
			<a href="javascript:void(0)" class='a_tab'>
				Đã đăng ký</a></li>
	</ul>
	<div class="clear"> </div>
</div>
<div class="clear"> </div>
<?php $this->inlineScript()->captureStart();?>
	$(".vd-button").on('click', function(){
		var _this = $(this);
		if(_this.hasClass('vd-button-active')){
			_this.removeClass('vd-button-active');

			var sub_count = $(".subscribe-count").attr('data-count');
			var new_count = parseInt(sub_count) - 1;
			$(".subscribe-count").attr('data-count', new_count);
			$(".subscribe-count").html(new_count);
			$(".subscribe-label").attr('aria-label', "Đăng ký").html("Đăng ký");
		}else{
			_this.addClass('vd-button-active');
			
			var sub_count = $(".subscribe-count").attr('data-count');
			var new_count = parseInt(sub_count) + 1;
			$(".subscribe-count").attr('data-count', new_count);
			$(".subscribe-count").html(new_count);
			$(".subscribe-label").attr('aria-label', "Hủy đăng ký").html("Hủy đăng ký");
		}
	});
<?php $this->inlineScript()->captureEnd();?>