<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
	$list = isset($this->list) ? $this->list : array();
	$page = isset($this->page) ? $this->page : 1;
	$filter = isset($this->filter) ? $this->filter : 1;
	$ac_name = isset($this->ac_name) ? $this->ac_name : '';
	$isWidget = (isset($this->is_widget) && $this->is_widget == 'widget') ? true:false;
	$total = Zend_Registry::isRegistered('total') ? Zend_Registry::get('total') : isset($this->total) ? $this->total : 1;
?>
<div class='separator'></div>
<?php if(count($list) > 0):?>
	<?php foreach ($list as $video):?>
	<?php $imgLink = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
		<div class='video-cover'>
			<div class='video-content'>
				<div class="video-inner margin-left" style='min-height: 400px;'>
					<a href="<?php echo node_link('video', $video);?>">
						<img src="<?php echo $imgLink;?>" title="<?php echo $video['name'];?>"
						style='width: 98%;height: 372px;'>
						<img class="tidypics-photo-start" width="35px" height="25px" 
							src="<?php echo ASSETS_CDN?>/img/play_youtube.png" 
							style="left: 43%; position: absolute; top: 41%; width: 82px; 
							height: 54px; cursor: pointer; background: none repeat scroll 0 0 rgba(0, 0, 0, 0) !important;box-shadow : none;">
						</a>
				</div>
			</div>
			
			<div class='action-content'>
				<?php 
					$views = isset($video['counter']['vyt']) ? $video['counter']['vyt'] : 0;
					$likes = isset($video['counter']['l']) ? $video['counter']['l'] : 0;
					$comments = isset($video['counter']['c']) ? $video['counter']['c'] : 0;
				?>
				<div class="title margin-left">
					<h3 style='font-weight: bold;'>
						<a href="<?php echo node_link('video', $video);?>" 
							style='cursor: pointer; color: #1e5dad;'>
							<?php echo $video['name'];?> </a></h3>
				   <div class="uinfo">
                            	bởi <a href="<?php echo user_link($video['u']);?>" 
                            		class='user-link'>
								<?php echo $video['u']['name'];?></a>
								<span class="timeago" 
								title="<?php echo convert_ts_to_js($video['ts']);?>"></span>
							</div>
				</div>
			    <div class="p-stats">
					<span class="views" title="Lượt xem">
						<?php $video['counter']['vyt'] = isset($video['counter']['vyt']) ? $video['counter']['vyt'] : 0;?>
						<img src="<?php echo ASSETS_CDN?>/img/views.png" 
								title="<?php echo number_format($views);?> lượt xem">
								<?php echo number_format($views);?></span>
                	<span class="comments">
                		<img src="<?php echo ASSETS_CDN?>/img/icon-comment.png" title="Link">
                			<?php echo $comments;?></span>
                </div>
                <div class='clear'></div>
                <div class="like-box">
					<ul class="share-links">
						<li>
					         <div class="fb-like" 
								data-href="<?echo SITE_URL;?><?php echo node_link('video',$video);?>"  
		                        data-layout="button_count" 
		                        data-action="like" 
		                        data-show-faces="true" 
		                        data-share="true">
		                     </div>
		                </li>     
		                 <li>
				        	<a>
                              <div class="g-plusone" 
                              	data-href="<?echo SITE_URL;?><?php echo node_link('video',$video);?>"
                              	data-count=true data-width="100"></div>
                              </a>
		                </li>
				    </ul>
                </div>
			</div>
		</div>
		<div class='separator-high' style='border-bottom: 1px solid #DDD;'></div>
		<div class='separator-high'></div>
	<?php endforeach;?>
<?php endif;?>
<div class="clear"> </div>
<ul class="dc_pagination dc_paginationA dc_paginationA03" id= "nav-footer">
  <li style='width: 100%; text-align: center' class='<?php if ($page == $total):?>disabled<?php Endif;?>'>
  	<?php 
  		$nextPage = $page + 1;
  		if($page != $total):
  			$nextWidget = "/$filter/{$nextPage}/widget";
  		else:
  			$nextWidget = "#/widget";
  		endif;
  		
  		if(isset($this->is_search) && $this->is_search){
			$url = "/video/search-videos?ac_name={$ac_name}&items_per_page=-1&_cl_submit=Submit&page={$nextPage}";
		}else{
	  		$url = "/{$filter}/{$nextPage}"; 
		}
  	?>
  	<a href="<?php echo $url;?>" 
  		id='next-page' title='Cover còn nhiều lắm, click tiếp đi nha'
  		data-href-widget="<?php echo $nextWidget;?>"
  		class="first" 
  		<?php if ($page == $total):?>
  			style='background: none repeat scroll 0 0 #1E5DAD; color: #FFF !important;'
  			<?php endif;?>>
  			<?php if ($page == $total):?>
  				:(( Xin lỗi bạn, chúng tôi sẽ tiếp tục cập nhật thêm dữ liệu
  			<?php else:?>
  			Cover còn nhiều lắm, click tiếp đi nha
  			<?php endif;?></a></li>
</ul>
<div class="clear"> </div>
<?php if (!$isWidget):?>
	<ul class="dc_pagination dc_paginationA dc_paginationA03"
		style='font-weight:bold;display:none;' id="loading">
	  <li style='width: 100%; text-align: center'>
	  	<a href='#' 
	  		class="first">Anh Zai chờ chút nha............</a></li>
	</ul>
<?php endif;?>