<div id="reminder_page">
	<div>
		<h1>Video bạn muốn tìm không xuất hiện???</h1>
		<h2>Hãy thực hiện các bước sau:<br></h2>
		<ol>
		<li><span>Kiểm tra lại từ khóa có thể bạn đã gõ sai (ví dụ: No love =&gt; na love).</span></li>
		<li><span>Nếu vẫn không tìm thấy, hãy thử 1 từ khóa khác</span></li>
		<li><span>Hãy dùng từ khóa ngắn hơn và đơn giản hơn</span></li>
		<li><span>Chúc bạn vui vẻ tại CoverVideos.vn!!!<br>
		</li>
		</ol>
	</div>                    
</div>
<style>
#reminder_page h1 {
    color: #114A8A;
    font-size: 24px;
}
#reminder_page h2 {
    color: #114A8A;
    font-size: 16px;
}
#reminder_page ol {
    color: #114A8A;
    font-weight: bold;
    list-style-type: decimal;
    margin: 0;
    padding: 0 26px;
}
#reminder_page ol li {
    line-height: 36px;
}
#reminder_page li span {
    color: #7D7D7D;
    font-weight: normal;
}
</style>