<?php 
    $row = $this->row;
    $user = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
    $newVideos = isset($this->newVideos) ? $this->newVideos : array();
    $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();

    $lu = $this->row;
    $step = get_value('_cl_step', '');
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>
<?php echo $this->render('/widget/user_menu.phtml');?>
<div class="inner-page" style='margin-left: 212px; width: 54%;'>
	<div class="searchbar">
		<div class="search-left">
			<?php echo $this->render('/widget/search-box.phtml');?>
		</div>
		<div class="search-right">
			<p>Tài khoản cá nhân</p>
		</div>
		<div class="clear"> </div>
	</div>
	<div id='vd_form'>
		<?php echo $this->form;?>
	</div>
</div>
<div class="right-content">
	<?php echo $this->render('/video/hot-videos.phtml');?>
	<div class="clear"> </div>
	<?php echo $this->render('/video/new-videos.phtml');?>
</div>
<div class="clear"> </div>
<?php $this->inlineScript()->captureStart();?>
CL.formStep = '<?php echo $step;?>';
CL.uid = '<?php echo $lu['id'];?>';
CL.CODENAME = '<?php echo CODENAME;?>';
<?php $this->inlineScript()->captureEnd();?>
<?php $this->inlineScript()->captureStart();?>
	$(function(){
		$('form').ajaxForm(
		{
			success: function(data, statusText, xhr, $form){
				if (data.success)
				{
					alert_success("Success!");
					$form.parent().find('span').html($form.find("input:text").val());
					$form.parent().find("span,.edit").show();
                    $('a.cancel').trigger('click');
				}
				else
					alert_error("error " + data.err);
			}
		}
		);
	});
	var src = $('.display_avatar .img-polaroid').attr('src');
	if(typeof src == 'undefined' || src == ''){
		$('.display_avatar .img-polaroid').attr('src',<?php echo ASSETS_CDN.'/img/no-image.jpg';?>);
	}
<?php $this->inlineScript()->captureEnd();?>
<style>
<!--
.display_avatar{
	background: none repeat scroll 0 0 #FFFFFF;
	box-shadow: 0 0 10px #E4E4E4;
	padding: 10px;
	margin: 16px;
	width: 400px;
	height: auto;
	float: right;
}
-->
</style>