<?php 
    $row = $this->row;
    $user = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
    $newVideos = isset($this->newVideos) ? $this->newVideos : array();
    $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();
    $playlist = isset($user['playlist']) ? $user['playlist'] : array();
    $uploadList = $this->uploadList;
    
    $strUploadList = get_string_ytid($uploadList);
    $strPlaylistVid = get_string_ytid($playlist);
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>
<?php echo $this->render('/widget/user_menu.phtml');?>
<div class="inner-page" style='margin-left: 212px; width: 62%; min-height: 700px;'>
	<?php echo $this->render('/widget/user-cover.phtml');?>
	
	<div >
		<div id='player'></div>
		<?php /*
			<iframe width="100%" height="495" style='margin-top: 10px;' 
				src="http://www.youtube.com/embed/<?php echo $firstVid;?>?playlist=<?php echo $strPlaylistVid;?>" 
					frameborder="0" allowfullscreen></iframe>
		*/?>
	</div>
	
	<div class='clear' style='margin-bottom: 20px;'></div>
	<div>
	 	<div class="fb-comments" 
	     	data-href="<?php echo SITE_URL . user_link($user);?>" data-width="800" 
	     		data-num-posts="10"></div>
     </div>
</div>
<div class="right-content" style='margin-top: 44px;width: 20%;'>
    <?php $this->user_view = true;?>
	<?php echo $this->render('/video/new-videos.phtml');?>
</div>
<div class="clear"> </div>
<?php $this->inlineScript()->captureStart();?>
  var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('player', {
      height: '495',
      width: '100%',
     loadPlaylist:{
        listType:'playlist',
        list:[<?php echo $strPlaylistVid;?>],
        index:parseInt(0),
        suggestedQuality:'small'
     },
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }
  function onPlayerReady(event) {
    event.target.loadPlaylist([<?php echo $strPlaylistVid;?>]);
  }
  var done = false;
  function onPlayerStateChange(event) {
    if (event.data == YT.PlayerState.PLAYING && !done) {
     // setTimeout(stopVideo, 60000);
      done = true;
    }
  }
  function stopVideo() {
    player.stopVideo();
  }
  
  $("#upload_video").click(function(){
  	  player.stopVideo();
  	  player.loadPlaylist([<?php echo $strUploadList;?>]);
  });
  
  $("#playlist_video").click(function(){
  	  player.stopVideo();
  	  player.loadPlaylist([<?php echo $strPlaylistVid;?>]);
  });
<?php $this->inlineScript()->captureEnd();?>