<?php 
    $row = $this->row;
    $user = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
    $newVideos = isset($this->newVideos) ? $this->newVideos : array();
    $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>

<div class="inner-page">
	<div class="searchbar">
		<div class="search-left">
			<?php echo $this->render('/widget/search-box.phtml');?>
		</div>
		<div class="search-right">
			<p>Chi tiết video</p>
		</div>
		<div class="clear"> </div>
	</div>
</div>
<div class="right-content">
	<?php echo $this->render('/video/hot-videos.phtml');?>
	<div class="clear"> </div>
	<?php echo $this->render('/video/new-videos.phtml');?>
</div>
<div class="clear"> </div>	