<?php $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();?>
<div class="popular">
	<h3>
		<a href="/hot" style='color: #FFF;'>
			Video phổ biến</a></h3>
	<p><img src="http://test.local/videostube-pack/web/images/l1.png" title="likes" /> 10,000</p>
	<div class="clear"> </div>
</div>
<?php if(count($hotVideos) > 0):?>
	<?php foreach ($hotVideos as $video):?>
		<?php $avatar = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
		<div class="grid1">
			<a href="<?php echo node_link('video', $video);?>">
				<h3 style='color: #1E5DAD;'><?php echo $video['name'];?></h3></a>
			<a href="<?php echo node_link('video', $video);?>"><img src="<?php echo $avatar;?>" 
				title="<?php echo $video['name'];?>" /></a>
			<div class="time1">
				<span><?php echo gmdate("H:i:s", (int)$video['duration']);?></span>
			</div>
			
			<div class="grid-info">
				<div class="video-share">
					<ul>
						<li><a href="#"><img src="http://test.local/videostube-pack/web/images/likes.png" title="links" /></a></li>
						<li><a href="#"><img src="http://test.local/videostube-pack/web/images/link.png" title="Link" /></a></li>
						<li><a href="#"><img src="http://test.local/videostube-pack/web/images/views.png" title="Views" /></a></li>
					</ul>
				</div>
				<div class="video-watch">
					<a href="<?php echo node_link('video', $video);?>">Xem ngay</a>
				</div>
				<div class="clear"> </div>
				<div class="lables">
					<p>Tags:<a href="#">Lorem</a></p>
				</div>
			</div>
		</div>
	<?php endforeach;?>
<?php endif;?>