<?php echo sand_dev_info_phtml(__FILE__);?>
<?php $hotVideos = isset($this->hotVideos) ? $this->hotVideos : array();?>
<div class="popular">
	<h3>
		<a href="/hot" style='color: #FFF;'>
			Video phổ biến</a></h3>
	<p><img src="<?php echo ASSETS_CDN?>/img/l1.png" title="likes" /> Vote</p>
	<div class="clear"> </div>
</div>
<?php if(count($hotVideos) > 0):?>
	<?php foreach ($hotVideos as $video):?>
		<?php $avatar = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
		<div class="grid1">
			<a href="<?php echo node_link('video', $video);?>">
				<h3 style='color: #1E5DAD;'><?php echo $video['name'];?></h3></a>
			<a href="<?php echo node_link('video', $video);?>"><img src="<?php echo $avatar;?>" 
				title="<?php echo $video['name'];?>" /></a>
			<div class="time1">
				<span><?php echo gmdate("H:i:s", (int)$video['duration']);?></span>
			</div>
			
			<div class="grid-info">
				<div class="video-share">
					<ul>
						<?php 
							$views = isset($video['counter']['vyt']) ? $video['counter']['vyt'] : 0;
							$likes = isset($video['counter']['l']) ? $video['counter']['l'] : 0;
							$comments = isset($video['counter']['c']) ? $video['counter']['c'] : 0;
						?>
						<li>
							<img src="<?php echo ASSETS_CDN?>/img/likes.png" title="links">
							<?php echo $likes;?>
							</li>
						<li>
							<img src="<?php echo ASSETS_CDN?>/img/icon-comment.png" title="Link">
							<?php echo $comments;?>
							</li>
						<li>
							<img src="<?php echo ASSETS_CDN?>/img/views.png" 
								title="<?php echo number_format($views);?> lượt xem">
								<?php echo number_format($views);?>
								</li>
					</ul>
				</div>
				<div class="video-watch">
					<a href="<?php echo node_link('video', $video);?>">Xem ngay</a>
				</div>
				<div class="clear"> </div>
				<?php if(isset($video['tags']) && count($video['tags']) > 0):?>
					<div class="lables">
						<p>Tags:
							<?php foreach ($video['tags'] as $tag):?>
								<a href="<?php echo tag_link($tag);?>">
									<?php echo $tag['name'];?>
								</a>
							<?php endforeach;?>
						</p>
					</div>
				<?php endif;?>
			</div>
		</div>
	<?php endforeach;?>
<?php endif;?>