<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
	$newVideos = isset($this->newVideos) ? $this->newVideos : array();
?>
<div class="Recent-Vodeos">
	<h3>Video mới nhất</h3>
	<?php if(count($newVideos) > 0):?>
		<?php foreach ($newVideos as $video):?>
			<?php $avatar = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
			<div class="video1">
			  <a href="<?php echo node_link('video', $video);?>">
				<img src="<?php echo $avatar;?>" 
					title="<?php echo $video['name'];?>" />
				<span>
				<?php if(strlen($video['name']) > 46):?>
					<?php echo char_breadcumb($video['name'], 46) . ' .....';?>
				<?php else:?>
					<?php echo $video['name'];?>
				<?php endif;?>
				</span>
				<?php $views = isset($video['counter']['vyt']) ? $video['counter']['vyt'] : 0;?>
			    <p style='height: 40px; overflow: hidden;' title='Luợt xem trên trang youtube'>
			    	<img src="<?php echo ASSETS_CDN?>/img/views.png" class='view_img'
							title="<?php echo number_format($views);?> lượt xem">
							  <?php echo number_format($views);?>
			    </p>
				<div class="clear"> </div>
			   	</a>
			</div>
		<?php endforeach;?>
	<?php endif;?>
	<div class="r-all">
		<a href="/new">Xem tất cả</a>
	</div>
</div>