<?php $newVideos = isset($this->newVideos) ? $this->newVideos : array();?>
<div class="Recent-Vodeos">
	<h3>Video mới nhất</h3>
	<?php if(count($newVideos) > 0):?>
		<?php foreach ($newVideos as $video):?>
			<?php $avatar = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
			<div class="video1">
			  <a href="<?php echo node_link('video', $video);?>">
				<img src="<?php echo $avatar;?>" 
					title="<?php echo $video['name'];?>" />
				<span><?php echo $video['name'];?></span>
				<p style='height: 40px; overflow: hidden;'><?php echo $video['content'];?> </p>
				<div class="clear"> </div>
			   	</a>
			</div>
		<?php endforeach;?>
	<?php endif;?>
	<div class="r-all">
		<a href="#">Xem tất cả</a>
	</div>
</div>