<?php echo sand_dev_info_phtml(__FILE__);?>
<?php 
	$newVideos = isset($this->newVideos) ? $this->newVideos : array();
?>
<div class="Recent-Vodeos">
	<h3>Video mới nhất</h3>
	<?php if(count($newVideos) > 0):?>
		<?php foreach ($newVideos as $video):?>
			<?php $avatar = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
			<div class="video1">
			  <a href="<?php echo node_link('video', $video);?>">
				  <div class="thumb">
					<img src="<?php echo $avatar;?>" 
						title="<?php echo $video['name'];?>" />
						<div class="duration">
							<?php $video['duration'] = isset($video['duration']) ? $video['duration'] : 0;?>
							<?php echo gmdate("H:i:s", (int)$video['duration']);?>
						</div>
					</div>
				<div class='info'>
					<span>
						<?php if(strlen($video['name']) > 46):?>
							<?php echo char_breadcumb($video['name'], 46) . ' .....';?>
						<?php else:?>
							<?php echo $video['name'];?>
						<?php endif;?>
					</span>
					<?php $views = isset($video['counter']['vyt']) ? $video['counter']['vyt'] : 0;?>
				    <p style='height: 40px; overflow: hidden;' title='Luợt xem trên trang youtube'>
				    	<?php echo gen_icon('eye-open');?>
								  <?php echo number_format($views);?>
				    </p>
				</div>
				<div class="clear"> </div>
			   	</a>
			</div>
		<?php endforeach;?>
	<?php endif;?>
	<div class="r-all">
		<a href="/new">Xem tất cả</a>
	</div>
</div>