

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">demo.com</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Homie</a></li>
              <li class="active"><a href="/site/admin">Admin home</a></li>
              <li><a href="/user/search" target="_blank">User</a></li>
              <li><a href="/#apps">Mobile apps</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>