<?php $lu = Zend_Registry::get('user');?>
<div class="navbar navbar-default navbar-fixed-top" id='user_menu'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><i class='<?php echo get_icon('home', $type = 'glyph');?>'></i></a>
        </div>
        
        <div class="navbar-collapse collapse">
        
          <ul class="nav navbar-nav" id='left-main-menu' >
				<li class="dropdown hover">
            	 <a href="/site/admin" style='text-transform: uppercase; font-weight: bold;'>
                    Trang quản trị</a>
          		</li>
              		
				</ul>
        </div><!--/.nav-collapse -->
 </div>