<?php 
	$u = Zend_Registry::get('user') ? Zend_Registry::get('user') : array();
?>
<div class="header">
	<!----start-Logo---->
	<div class="logo">
		<a href="/"><img title="logo" src="http://test.local/videostube-pack/web/images/logo.png"
			style='height: 55px;'></a>
	</div>
	<!----End-Logo---->
	<!----start-top-nav---->
	<div class="top-nav">
		<ul>
			<li><a href="/">Trang chủ</a></li>
			<li><a href="/new">Mới nhất</a></li>
			<li><a href="/hot">Hot nhất</a></li>
			<li><a href="/domestic">Trong nước</a></li>
			<li><a href="/foreign">Nước ngoài</a></li>
			<li><a href="contact.html">Liên lạc</a></li>
			<?php if (has_perm('sudo', null, '', $u)) :?>
				<li><a href="/site/admin">Quản trị</a></li>
			<?php endif;?>
		</ul>
	</div>
	<div class="clear"> </div>
	<!----End-top-nav---->
</div>
		
<div class="clear"> </div>