<?php 
	$u = Zend_Registry::get('user') ? Zend_Registry::get('user') : array();
	$filter = isset($this->active_filter) ? $this->active_filter : '';
	$is_home = isset($this->is_home) ? $this->is_home : false;
?>
<div class="header">
	<!----start-Logo---->
	<div class="logo">
		<a href="/"><img title="logo" src="<?php echo ASSETS_CDN?>/img/logo.png"
			style='height: 49px;'></a>
	</div>
	<!----End-Logo---->
	<!----start-top-nav---->
	<div class="top-nav">
		<ul>
			<li <?php if($filter == '' && $is_home):?> class='active' <?php endif;?>>
				<a href="/">Trang chủ</a></li>
			<li <?php if($filter == 'new'):?> class='active' <?php endif;?>>
				<a href="/new">Mới nhất</a></li>
			<li <?php if($filter == 'hot'):?> class='active' <?php endif;?>>
				<a href="/hot">Hot nhất</a></li>
			<li <?php if($filter == 'domestic'):?> class='active' <?php endif;?>>
				<a href="/domestic">Trong nước</a></li>
			<li <?php if($filter == 'foreign'):?> class='active' <?php endif;?>>
				<a href="/foreign">Nước ngoài</a></li>
		    <?php if($u != null && !has_perm('sudo', null, '', $u)):?>
	    		<li>
					<a href="<?php echo user_link($u);?>">Trang cá nhân</a></li>
		    <?php endif;?>
			<?php if (has_perm('sudo', null, '', $u)) :?>
				<li><a href="/site/admin">Quản trị</a></li>
			<?php endif;?>
		</ul>
	</div>
	<div class="clear"> </div>
	<!----End-top-nav---->
</div>
		
<div class="clear"> </div>