<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');

?>
<!DOCTYPE html>
<html>
	<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Bootstrap::$pageTitle;?> - <?php echo SITE_NAME;?></title>
    <meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery.js"></script>
    <link rel="shortcut icon" href="//www.groupon.com/layout/assets/gig_application_layout-favicon-5414457d50.ico">
    <link href="<?php echo ASSETS_CDN;?>/css/facebook.css" rel="stylesheet" type="text/css" />
    
<?php //if (APPLICATION_ENV == 'development') :?>
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/reset.css" media="screen" rel="stylesheet" type="text/css" >
    
    <link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css" rel="stylesheet" type="text/css"/>	
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css" >
    
    <link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo ASSETS_CDN;?>/css/jquery.datetimepicker.css" rel="stylesheet">
    <script src="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/js/bootstrap.min.js"></script>		
<style>
div.navbar ul.breadcrumb > li
{
	min-height:30px;
	padding-top:10px;
}
#tsCategory { position: absolute; }
.fileinput-button input{
	border-width: 0 !important;
}
#user_menu{
	background-color: #000;
	height: 40px;
}
</style>
<?php 
$format = "DD/MM/YYYY";
?>

<script type='text/javascript'>
<?php echo $this->render('widget/php-to-js.phtml');?>
CL.DATE_FORMAT = "<?php echo substr(strtolower($format), 0, -2);?>";
</script>
	
</head>
<body class='prom-night ltr en_US en_XX'> 
<div id="global-container" style="display: block;">
<?php echo $this->render("admin_menu.phtml");?>
<div class='container'>
    <div class='row' style='min-height:65px;'></div>
</div>

<div class='container' style='min-height:500px;' >
     <?php echo $this->layout()->content; ?>
</div>

<div class='container' style='background-color:#222222;padding:30px;margin-top:30px;'>
<footer>
	<div style='color:#888888; text-align: center;'>			
		<a title='Trang chủ' href="/" style='color:white;'>
		<i style='color:white;' class='<?php echo get_icon('home');?>'></i></a>
		
		<a style='color:#888888;'href="/page/about.html">Thông tin</a>
		|
		<a style='color:#888888;' href="/page/terms.html">Điều khoản</a>
		|
		<a style='color:#888888;' href="/page/contact.html">Liên hệ</a>
	</div>
	<div style='color:#888888; text-align: center;'>
	      <span style='color:#888888;'><?php echo SITE_NAME;?>: </span>  
	      <a style='color:#888888;'target="_blank" href="https://www.facebook.com/<?php echo SITE_NAME;?>">Facebook</a>
	      |
	      <a style='color:#888888;'target="_blank" href="https://twitter.com/<?php echo SITE_NAME;?>">Twitter</a>
	      |		    
	      <a  style='color:#888888;' target="_blank" href="https://itunes.apple.com">iOS</a>
	      |
		  <a   style='color:#888888;' target="_blank" href="https://play.google.com">Android</a>
	</div>
	<div style='color:#888888; text-align: center;'>
	<p style='color:#888888;'>&copy; <b>2013 <?php echo preg_replace('/^http:\/\//', '', SITE_URL)?></b></p>
	</div>				
</footer>
</div>
  
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery-ui-1.8.16.custom.min.js"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/javascript/jquery.toastmessage.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/3rdparty/underscore-min.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/utils.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.form.js" type="text/javascript"></script>
    <?php /***********JQUERY*************/?>
    <script src="<?php echo ASSETS_CDN;?>/js/en.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/site.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/vi.js"></script>
    <?php /*
    */?>
    
    <?php /***********HOME ASSETS*************/?>
    <link href="<?php echo ASSETS_CDN;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css" >
    
    <script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/src/jquery.tokeninput.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/styles/token-input-facebook.css" />
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax_metadata_config.js" type="text/javascript"></script>
    <script type="text/javascript" src="<?php echo ASSETS_CDN;?>/tinymce/tinymce_3.5.2/jscripts/tiny_mce/tiny_mce.js"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/comment.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/site_common.js" type="text/javascript"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/jquery.datetimepicker.js"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/autoresize.jquery.js" type="text/javascript"></script>
<?php echo $this->headScript();?>
<?php print $this->inlineScript();?>
</div>
</body>
</html>

