<?php 
	$u = Zend_Registry::get('user') ? Zend_Registry::get('user') : array();
	$filter = isset($this->active_filter) ? $this->active_filter : '';
	$is_home = isset($this->is_home) ? $this->is_home : false;
?>
<header id="top-nav" class="badge-sticky-nav header">
	<div class="nav-wrap">
		<h1>
			<a>Cover Hay</a>
		</h1>
		
		<div class="headbar-items">
			<ul>
				<li>
					<a href="/" <?php if($filter == ''):?> class='selected' <?php endif;?>>
						<span class='label'>Trang chủ</a></span></li>
				<li>
					<a href="/vote" <?php if($filter == 'vote'):?> class='selected' <?php endif;?>>
						<span class="label">Bình chọn</span></a></li>
				<li>
					<a href="/hot" <?php if($filter == 'hot'):?> class='selected' <?php endif;?>>
						<span class="label">Hot nhất</span></a></li>
				<li>
					<a href="/domestic" <?php if($filter == 'domestic'):?> class='selected' <?php endif;?>>
						<span class="label">Trong nước</span></a></li>
				<li>
					<a href="/foreign" <?php if($filter == 'foreign'):?> class='selected' <?php endif;?>>
						<span class="label">Nước ngoài</span></a></li>
			</ul>
		</div>
		
		<div class="visitor-function" id="jsid-visitor-function">
			<?php if(is_guest()):?>
			<a href="/user/login" class="badge-login-button link"
				title="Đăng nhập">Đăng nhập</a>
        	<a href="/user/register" class="badge-signup-button link"
        		title="Đăng ký">Đăng ký</a>
			<?php else:?>
			    <?php if(!has_perm('sudo', null, '', $u)):?>
			    	<?php $avatar = (isset($u['avatar']) && $u['avatar'] != '') ? $u['avatar'] : default_avatar('user');?>
		    		<a href="<?php echo user_link($u);?>" class='avatar'>
					    <img title="Trang cá nhân" src="<?php echo $avatar;?>"></a>
			    <?php endif;?>
				<?php if (has_perm('sudo', null, '', $u)) :?>
		        	<a href="/site/admin" class="badge-signup-button link"
        				title="Quản trị">Quản trị</a>
				<?php endif;?>
					<a href="/user/logout" class="badge-signup-button link"
        				title="Đăng suất">Đăng suất</a>
			<?php endif;?>
            <div class="upload">
            	<a href="/video/new" 
            		class="badge-signup-button upload">Upload</a>
            </div>
	    </div>
	</div>
</header>
<?php /*
<div class="header">
	<!----start-Logo---->
	<div class="logo">
		<a href="/" style='margin-right: 15px;'>
			<img title="Trang chủ" src="<?php echo ASSETS_CDN?>/img/logo.png"
			style='height: 42px;'></a>
		<?php if(!is_guest()):?>
			<a href="/video/new">
				<img title="Thêm video mới" src="<?php echo ASSETS_CDN?>/img/upload_big.jpeg"
				style='height: 42px;'></a>
		<?php endif;?>
	</div>
	<!----End-Logo---->
	<!----start-top-nav---->
	<div class="top-nav">
		<ul>
			<li <?php if($filter == '' && $is_home):?> class='active' <?php endif;?>>
				<a href="/">
					<span class='li-home'>Trang chủ</a></span></li>
			<li <?php if($filter == 'vote'):?> class='active' <?php endif;?>>
				<a href="/vote">
					<span class='li-home'>Bình chọn</span></a></li>
			<li <?php if($filter == 'hot'):?> class='active' <?php endif;?>>
				<a href="/hot">
					<span class='li-home'>Hot nhất</span></a></li>
			<li <?php if($filter == 'domestic'):?> class='active' <?php endif;?>>
				<a href="/domestic">
					<span class='li-home'>Trong nước</span></a></li>
			<li <?php if($filter == 'foreign'):?> class='active' <?php endif;?>>
				<a href="/foreign">
					<span class='li-home'>Nước ngoài</span></a></li>
			<?php if(is_guest()):?>
				<li style='padding: 4px;'>
					<a href="/user/login">
				    	<img title="Đăng nhập" src="<?php echo ASSETS_CDN?>/img/login-icon.png"
							style='height: 37px;'></a></li>
				<li style='padding: 4px;'>
					<a href="/user/register">
				    	<img title="Đăng ký" src="<?php echo ASSETS_CDN?>/img/register.png"
							style='height: 37px;'></a></li>
			<?php else:?>
			    <?php if(!has_perm('sudo', null, '', $u)):?>
			    	<?php $avatar = (isset($u['avatar']) && $u['avatar'] != '') ? $u['avatar'] : default_avatar('user');?>
		    		<li style='padding: 4px;'><a href="<?php echo user_link($u);?>">
					    <img title="Trang cá nhân" src="<?php echo $avatar;?>"
								style='height: 37px; width:40px;'></a></a></li>
			    <?php endif;?>
				<?php if (has_perm('sudo', null, '', $u)) :?>
					<li><a href="/site/admin">
						    <span class='li-home'>Quản trị</span></a></li>
				<?php endif;?>
					<li style='padding: 4px;'><a href="/user/logout">
					    <img title="Đăng xuất" src="<?php echo ASSETS_CDN?>/img/logout.png"
								style='height: 37px;'></a></a></li>
			<?php endif;?>
		</ul>
	</div>
	<div class="clear"> </div>
	<!----End-top-nav---->
</div>
*/ ?>
<div class="clear"> </div>