<div class="footer" id='nav-footer'>
	<div class="wrap" style='width: 84%;'> 
		<div class="box2">
		<h4>Cover Videos</h4>
				<ul>
					<li><a href="/">Trang chủ</a></li>
					<li><a href="/new">Mới nhất</a></li>
					<li><a href="/hot">Hot nhất</a></li>
					<li><a href="/domestic">Trong nước</a></li>
					<li><a href="/foreign">Nước ngoài</a></li>
				</ul>
				<div class="clear"> </div>
				<ul>
					<li><a href="#"
					style='font-size: 0.8em;'>@Copyright 2014. Cover Videos VietNam</a></li>
				</ul>
		</div>
		<div class="box1">
		<h4>Cập nhật clip trên facebook</h4>
				<ul class="social">
					<li><img title="facebook" 
						src="<?php echo ASSETS_CDN?>/img/facebook.png">
							<a href="https://www.facebook.com/clipcoverhay">Facebook</a></li>
				</ul>
		</div>
		<div class="clear"> </div>
	</div>
</div>