<div class="footer">
	<div class="wrap"> 
		<div class="box1">
		<h4>Ur's Account</h4>
				<ul>
					<li><a href="#">My Channel</a></li>
					<li><a href="#">Subscribtion</a></li>
					<li><a href="#">Locations</a></li>
					<li><a href="#">Favorites</a></li>
					<li><a href="#">Add</a></li>
					<li><a href="#">Ur-specials</a></li>
					<li><a href="#">Submission Rules</a></li>
				</ul>
		</div>
		<div class="box1">
		<h4>Policy &amp; Terms</h4>
				<ul>
					<li><a href="#">Terms &amp; Conditions</a></li>
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Submission Rules</a></li>
					<li><a href="#">Company Buzz</a></li>
					<li><a href="#">My Staff</a></li>
					<li><a href="#">Moodle Hosting</a></li>
					<li><a href="#">OpenCart Hosting</a></li>
				</ul>
		</div>
		<div class="box1">
		<h4>Community</h4>
				<ul>
					<li><a href="#">Standard Support</a></li>
					<li><a href="#">Premier Support</a></li>
					<li><a href="#">Support Center</a></li>
					<li><a href="#">Host Affiliate</a></li>
					<li><a href="#">Infographics</a></li>
					<li><a href="#">indian Hosting</a></li>
					<li><a href="#">Green Web Hosting</a></li>
				</ul>
		</div>
		<div class="box1">
			<div class="hide-box">
		<h4>About Us</h4>
				<ul>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Terms of Service</a></li>
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Guarantee</a></li>
					<li><a href="#">Link to Us</a></li>
					<li><a href="#">We're Hiring</a></li>
				</ul>
		</div>
			</div>
		<div class="box1">
		<h4>Stay in touch on</h4>
				<ul class="social">
					<li><img title="facebook" src="http://test.local/videostube-pack/web/images/facebook.png"><a href="#">Facebook</a></li>
					<li><img title="twitter" src="http://test.local/videostube-pack/web/images/twitter.png"><a href="#">Twitter</a></li>
					<li><img title="google+" src="http://test.local/videostube-pack/web/images/gplus.png"><a href="#">Google+</a></li>
				</ul>
		</div>
		<div class="clear"> </div>
	</div>
</div>