<div class="footer" id='nav-footer'>
	<div class="wrap"> 
		<div class="box1">
		<h4>Ur's Account</h4>
				<ul>
					<li><a href="#">My Channel</a></li>
					<li><a href="#">Subscribtion</a></li>
				</ul>
		</div>
		<div class="box1">
		<h4>Policy &amp; Terms</h4>
				<ul>
					<li><a href="#">Terms &amp; Conditions</a></li>
					<li><a href="#">Privacy Policy</a></li>
				</ul>
		</div>
		<div class="box1">
		<h4>Community</h4>
				<ul>
					<li><a href="#">Standard Support</a></li>
					<li><a href="#">Premier Support</a></li>
				</ul>
		</div>
		<div class="box1">
			<div class="hide-box">
		<h4>About Us</h4>
				<ul>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Terms of Service</a></li>
				</ul>
		</div>
			</div>
		<div class="box1">
		<h4>Stay in touch on</h4>
				<ul class="social">
					<li><img title="facebook" src="http://test.local/videostube-pack/web/images/facebook.png"><a href="#">Facebook</a></li>
				</ul>
		</div>
		<div class="clear"> </div>
	</div>
</div>